# -*- python -*-
Import("env")
import glob, os, sys

import lsst.scons.tests
#
# Tests
#
ignoreList=[]
tests = lsst.scons.tests.Control(env, ignoreList=ignoreList, verbose=True)
    
for fileName in glob.glob("*.cc"):
    env.Program(fileName, LIBS=env.getlibs("utils") + env.gettestlibs("boost"))

tests.run("*.cc")

# set up python tests
for target in tests.run("*.py"):
    env.Depends(target, "../python/lsst/utils/utilsLib%s" % (env["LDMODULESUFFIX"]))
