# -*- python -*-
Import("env")
import os, sys

import lsst.sconsUtils.tests
#
# Tests
#
ignoreList=[]
tests = lsst.sconsUtils.tests.Control(env, ignoreList=ignoreList, verbose=True)
    
for fileName in Glob("*.cc"):
    env.Program(fileName, LIBS=env.getLibs("main test"))

tests.run("*.cc")

# set up python tests
for target in tests.run("*.py"):
    env.Depends(target, "#python")
