# -*- python -*-
Import('env')

env.SharedLibrary('utils', map(lambda str: "../src/" + str,
                            ["Demangle.cc",
                             "Utils.cc",
                             "RaDecStr.cc"
                            ]),
                  LIBS=env.getlibs("boost_regex pex_exceptions"))
