# -*- python -*-
Import('env')
import os

env.SharedLibrary('utils', map(lambda str: "../src/" + str,
                            ["Demangle.cc",
                             "Utils.cc"
                            ]), LIBS=env.getlibs("boost"))
