# -*- python -*-
Import('env')

env.SharedLibrary('utils', map(lambda str: "../src/" + str,
                            ["Demangle.cc",
                             "Utils.cc"
                            ]),
                  LIBS=filter(lambda x: x != "utils", env.getlibs("utils")))
