# -*- python -*-
Import("env")

env.CheckSwig("python", ilang="c++", includedProducts="pex_exceptions")
env.LoadableModuleIncomplete("_utilsLib", Split("utilsLib.i"), LIBS=env.libs["boost"] + ["pex_exceptions"] + ["utils"])
