name: Run mypy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          cache: "pip"

      - name: Install
        run: pip install mypy pydantic

      - name: Install third party stubs
        run: pip install types-requests types-PyYAML types-click types-pkg_resources types-Deprecated

      - name: Fake a version
        run: |
          echo "__all__ = ['__version__']" > python/lsst/utils/version.py
          echo "__version__ = '0.0.1'" >> python/lsst/utils/version.py

      - name: Run mypy
        run: mypy python/lsst
